/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pll.employee.directory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDirectory service. Represents a row in the &quot;pll_EmployeeDirectory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.pll.employee.directory.model.impl.EmployeeDirectoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.pll.employee.directory.model.impl.EmployeeDirectoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDirectory
 * @generated
 */
@ProviderType
public interface EmployeeDirectoryModel
	extends BaseModel<EmployeeDirectory>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee directory model instance should use the {@link EmployeeDirectory} interface instead.
	 */

	/**
	 * Returns the primary key of this employee directory.
	 *
	 * @return the primary key of this employee directory
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee directory.
	 *
	 * @param primaryKey the primary key of this employee directory
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this employee directory.
	 *
	 * @return the employee ID of this employee directory
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee directory.
	 *
	 * @param employeeId the employee ID of this employee directory
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this employee directory.
	 *
	 * @return the group ID of this employee directory
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee directory.
	 *
	 * @param groupId the group ID of this employee directory
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee directory.
	 *
	 * @return the company ID of this employee directory
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee directory.
	 *
	 * @param companyId the company ID of this employee directory
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee directory.
	 *
	 * @return the user ID of this employee directory
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee directory.
	 *
	 * @param userId the user ID of this employee directory
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee directory.
	 *
	 * @return the user uuid of this employee directory
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee directory.
	 *
	 * @param userUuid the user uuid of this employee directory
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this employee directory.
	 *
	 * @return the create date of this employee directory
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee directory.
	 *
	 * @param createDate the create date of this employee directory
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee directory.
	 *
	 * @return the modified date of this employee directory
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee directory.
	 *
	 * @param modifiedDate the modified date of this employee directory
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee name of this employee directory.
	 *
	 * @return the employee name of this employee directory
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this employee directory.
	 *
	 * @param employeeName the employee name of this employee directory
	 */
	public void setEmployeeName(String employeeName);

	/**
	 * Returns the designation of this employee directory.
	 *
	 * @return the designation of this employee directory
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this employee directory.
	 *
	 * @param designation the designation of this employee directory
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the extention number of this employee directory.
	 *
	 * @return the extention number of this employee directory
	 */
	@AutoEscape
	public String getExtentionNumber();

	/**
	 * Sets the extention number of this employee directory.
	 *
	 * @param extentionNumber the extention number of this employee directory
	 */
	public void setExtentionNumber(String extentionNumber);

	/**
	 * Returns the direct number of this employee directory.
	 *
	 * @return the direct number of this employee directory
	 */
	@AutoEscape
	public String getDirectNumber();

	/**
	 * Sets the direct number of this employee directory.
	 *
	 * @param directNumber the direct number of this employee directory
	 */
	public void setDirectNumber(String directNumber);

	/**
	 * Returns the mobile number of this employee directory.
	 *
	 * @return the mobile number of this employee directory
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this employee directory.
	 *
	 * @param mobileNumber the mobile number of this employee directory
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the alternate number of this employee directory.
	 *
	 * @return the alternate number of this employee directory
	 */
	@AutoEscape
	public String getAlternateNumber();

	/**
	 * Sets the alternate number of this employee directory.
	 *
	 * @param alternateNumber the alternate number of this employee directory
	 */
	public void setAlternateNumber(String alternateNumber);

	/**
	 * Returns the residence number of this employee directory.
	 *
	 * @return the residence number of this employee directory
	 */
	@AutoEscape
	public String getResidenceNumber();

	/**
	 * Sets the residence number of this employee directory.
	 *
	 * @param residenceNumber the residence number of this employee directory
	 */
	public void setResidenceNumber(String residenceNumber);

	/**
	 * Returns the fax number of this employee directory.
	 *
	 * @return the fax number of this employee directory
	 */
	@AutoEscape
	public String getFaxNumber();

	/**
	 * Sets the fax number of this employee directory.
	 *
	 * @param faxNumber the fax number of this employee directory
	 */
	public void setFaxNumber(String faxNumber);

	/**
	 * Returns the location of this employee directory.
	 *
	 * @return the location of this employee directory
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this employee directory.
	 *
	 * @param location the location of this employee directory
	 */
	public void setLocation(String location);

	/**
	 * Returns the department of this employee directory.
	 *
	 * @return the department of this employee directory
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this employee directory.
	 *
	 * @param department the department of this employee directory
	 */
	public void setDepartment(String department);

	/**
	 * Returns the blood group of this employee directory.
	 *
	 * @return the blood group of this employee directory
	 */
	@AutoEscape
	public String getBloodGroup();

	/**
	 * Sets the blood group of this employee directory.
	 *
	 * @param bloodGroup the blood group of this employee directory
	 */
	public void setBloodGroup(String bloodGroup);

	/**
	 * Returns the file entry ID of this employee directory.
	 *
	 * @return the file entry ID of this employee directory
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this employee directory.
	 *
	 * @param fileEntryId the file entry ID of this employee directory
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the present grade of this employee directory.
	 *
	 * @return the present grade of this employee directory
	 */
	@AutoEscape
	public String getPresentGrade();

	/**
	 * Sets the present grade of this employee directory.
	 *
	 * @param presentGrade the present grade of this employee directory
	 */
	public void setPresentGrade(String presentGrade);

	/**
	 * Returns the passport number of this employee directory.
	 *
	 * @return the passport number of this employee directory
	 */
	@AutoEscape
	public String getPassportNumber();

	/**
	 * Sets the passport number of this employee directory.
	 *
	 * @param passportNumber the passport number of this employee directory
	 */
	public void setPassportNumber(String passportNumber);

	/**
	 * Returns the passport validity of this employee directory.
	 *
	 * @return the passport validity of this employee directory
	 */
	public Date getPassportValidity();

	/**
	 * Sets the passport validity of this employee directory.
	 *
	 * @param passportValidity the passport validity of this employee directory
	 */
	public void setPassportValidity(Date passportValidity);

	/**
	 * Returns the anniversary of this employee directory.
	 *
	 * @return the anniversary of this employee directory
	 */
	public Date getAnniversary();

	/**
	 * Sets the anniversary of this employee directory.
	 *
	 * @param anniversary the anniversary of this employee directory
	 */
	public void setAnniversary(Date anniversary);

	/**
	 * Returns the uan number of this employee directory.
	 *
	 * @return the uan number of this employee directory
	 */
	@AutoEscape
	public String getUanNumber();

	/**
	 * Sets the uan number of this employee directory.
	 *
	 * @param uanNumber the uan number of this employee directory
	 */
	public void setUanNumber(String uanNumber);

	/**
	 * Returns the about me of this employee directory.
	 *
	 * @return the about me of this employee directory
	 */
	@AutoEscape
	public String getAboutMe();

	/**
	 * Sets the about me of this employee directory.
	 *
	 * @param aboutMe the about me of this employee directory
	 */
	public void setAboutMe(String aboutMe);

	@Override
	public EmployeeDirectory cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}