create table pll_EmployeeDirectory (
	employeeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	employeeName VARCHAR(75) null,
	designation VARCHAR(75) null,
	extentionNumber VARCHAR(75) null,
	directNumber VARCHAR(75) null,
	mobileNumber VARCHAR(75) null,
	alternateNumber VARCHAR(75) null,
	residenceNumber VARCHAR(75) null,
	faxNumber VARCHAR(75) null,
	location VARCHAR(75) null,
	department VARCHAR(75) null,
	bloodGroup VARCHAR(75) null,
	fileEntryId LONG,
	presentGrade VARCHAR(75) null,
	passportNumber VARCHAR(75) null,
	passportValidity DATE null,
	anniversary DATE null,
	uanNumber VARCHAR(75) null,
	aboutMe VARCHAR(75) null
);