/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package pll_master_schema.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Departments service. Represents a row in the &quot;pll_master_Departments&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>pll_master_schema.model.impl.DepartmentsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>pll_master_schema.model.impl.DepartmentsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Departments
 * @generated
 */
@ProviderType
public interface DepartmentsModel
	extends AuditedModel, BaseModel<Departments>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a departments model instance should use the {@link Departments} interface instead.
	 */

	/**
	 * Returns the primary key of this departments.
	 *
	 * @return the primary key of this departments
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this departments.
	 *
	 * @param primaryKey the primary key of this departments
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the department ID of this departments.
	 *
	 * @return the department ID of this departments
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this departments.
	 *
	 * @param departmentId the department ID of this departments
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the department of this departments.
	 *
	 * @return the department of this departments
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this departments.
	 *
	 * @param department the department of this departments
	 */
	public void setDepartment(String department);

	/**
	 * Returns the location ID of this departments.
	 *
	 * @return the location ID of this departments
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this departments.
	 *
	 * @param locationId the location ID of this departments
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the company ID of this departments.
	 *
	 * @return the company ID of this departments
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this departments.
	 *
	 * @param companyId the company ID of this departments
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this departments.
	 *
	 * @return the user ID of this departments
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this departments.
	 *
	 * @param userId the user ID of this departments
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this departments.
	 *
	 * @return the user uuid of this departments
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this departments.
	 *
	 * @param userUuid the user uuid of this departments
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this departments.
	 *
	 * @return the user name of this departments
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this departments.
	 *
	 * @param userName the user name of this departments
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this departments.
	 *
	 * @return the create date of this departments
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this departments.
	 *
	 * @param createDate the create date of this departments
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this departments.
	 *
	 * @return the modified date of this departments
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this departments.
	 *
	 * @param modifiedDate the modified date of this departments
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Departments cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}